insert into province (name) values ('BUENOS AIRES');
insert into province (name) values ('CATAMARCA');
insert into province (name) values ('CHACO');
insert into province (name) values ('CHUBUT');
insert into province (name) values ('CÓRDOBA');
insert into province (name) values ('CORRIENTES');
insert into province (name) values ('ENTRE RÍOS');
insert into province (name) values ('FORMOSA');
insert into province (name) values ('JUJUY');
insert into province (name) values ('LA PAMPA');
insert into province (name) values ('LA RIOJA');
insert into province (name) values ('MENDOZA');
insert into province (name) values ('MISIONES');
insert into province (name) values ('NEUQUÉN');
insert into province (name) values ('RÍO NEGRO');
insert into province (name) values ('SALTA');
insert into province (name) values ('SAN JUAN');
insert into province (name) values ('SAN LUIS');
insert into province (name) values ('SANTA CRUZ');
insert into province (name) values ('SANTA FÉ');
insert into province (name) values ('SANTIAGO DEL ESTERO');
insert into province (name) values ('TIERRA DEL FUEGO');
insert into province (name) values ('TUCUMÁN');